Update browser.py
Werkzeug was upgraded to 1.0.0 and introduced this error:
```ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/local/lib/python3.8/site-packages/werkzeug/__init__.py)```

Suggesting this change which has been tested locally and discussed here:
https://github.com/jmcarp/robobrowser/issues/93